"""initial

Revision ID: b569fc0a5c4c
Revises: 
Create Date: 2026-03-23 09:48:54.404964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b569fc0a5c4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workspace_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('agents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('boss', sa.String(), nullable=True),
    sa.Column('instructions_path', sa.String(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('is_removed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"), nullable=False),
    sa.ForeignKeyConstraint(['organization_name', 'boss'], ['agents.organization_name', 'agents.name'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_name'], ['organizations.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_name', 'name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_scope', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('consumed_input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consumed_output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"), nullable=False),
    sa.ForeignKeyConstraint(['organization_scope'], ['organizations.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_sequences',
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('next_number', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['organization_name'], ['organizations.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('assignee', sa.String(), server_default='user', nullable=False),
    sa.Column('queued_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"), nullable=False),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'failed', 'done', 'canceled')"),
    sa.ForeignKeyConstraint(['organization_name'], ['organizations.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_dispatch', 'tasks', ['queued_at'], unique=False, sqlite_where=sa.text("status = 'open' AND assignee != 'user'"))
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='running', nullable=False),
    sa.Column('started_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"), nullable=False),
    sa.Column('ended_at', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('consumed_input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consumed_output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('execution_steps', sa.Text(), server_default='[]', nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'failed', 'preempted')"),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))"), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')"),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_messages')
    op.drop_table('runs')
    op.drop_table('comments')
    op.drop_index('idx_tasks_dispatch', table_name='tasks', sqlite_where=sa.text("status = 'open' AND assignee != 'user'"))
    op.drop_table('tasks')
    op.drop_table('task_sequences')
    op.drop_table('sessions')
    op.drop_table('agents')
    op.drop_table('organizations')
    # ### end Alembic commands ###
