"""add_model_column_to_agents

Revision ID: d47fbc9edd39
Revises: b569fc0a5c4c
Create Date: 2026-03-23 13:08:50.601922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47fbc9edd39'
down_revision: Union[str, Sequence[str], None] = 'b569fc0a5c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'model')
    # ### end Alembic commands ###
